---
title: "Untitled"
author: "Sasha Haywood"
date: "3/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyr)
library(dplyr)
library(lpSolve)
library(irr)
library(readr)
```

The following demonstrates the difference between results from Krippendorfs Alpha and ICC doing an agreement test.
```{r}
options(scipen=999)

gunther <- read_csv("pre discussion expert group annotation/pre-gunther-Jews2020Jan-Apr.rep1.csv", 
    col_types = cols(`Antisemitism Rating` = col_factor(levels = c("1", 
        "2", "3", "4", "5"))))
jenna <- read_csv("pre discussion expert group annotation/pre-Jenna-Jews2020Jan-Apr.rep1.csv", 
    col_types = cols(`Antisemitism Rating` = col_factor(levels = c("1", 
        "2", "3", "4", "5"))))


gunther = data.frame(gunther[,c(1, 8)])
gunther = rename(gunther, gunther = Antisemitism.Rating)
jenna = data.frame(jenna[,c(1, 8)])
jenna = rename(jenna, jenna = Antisemitism.Rating)
experts = full_join(gunther, jenna, na_matches = "na")
experts = experts[,-1]
experts.t = t(experts)
kripp.alpha(experts.t, method = "ordinal")

n.experts = experts
n.experts$gunther = as.numeric(n.experts$gunther)
n.experts$jenna = as.numeric(n.experts$jenna)
icc(n.experts, model = "twoway", type = "agreement")
```